#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServisMobilnaAplikacija
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
using System.IO;
using System.IO.IsolatedStorage;
using Microsoft.Phone.Data.Linq.Mapping;
using Microsoft.Phone.Data.Linq;


public class DebugWriter : TextWriter
{
    private const int DefaultBufferSize = 256;
    private System.Text.StringBuilder _buffer;

    public DebugWriter()
    {
        BufferSize = 256;
        _buffer = new System.Text.StringBuilder(BufferSize);
    }

    public int BufferSize
    {
        get;
        private set;
    }

    public override System.Text.Encoding Encoding
    {
        get { return System.Text.Encoding.UTF8; }
    }

    #region StreamWriter Overrides
    public override void Write(char value)
    {
        _buffer.Append(value);
        if (_buffer.Length >= BufferSize)
            Flush();
    }

    public override void WriteLine(string value)
    {
        Flush();

        using(var reader = new StringReader(value))
        {
            string line; 
            while( null != (line = reader.ReadLine()))
                System.Diagnostics.Debug.WriteLine(line);
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            Flush();
    }

    public override void Flush()
    {
        if (_buffer.Length > 0)
        {
            System.Diagnostics.Debug.WriteLine(_buffer);
            _buffer.Clear();
        }
    }
    #endregion
}


	public partial class DatabaseContext : System.Data.Linq.DataContext
	{
		
		public bool CreateIfNotExists()
		{
			bool created = false;
			if (!this.DatabaseExists())
			{
				string[] names = this.GetType().Assembly.GetManifestResourceNames();
				string name = names.Where(n => n.EndsWith(FileName)).FirstOrDefault();
				if (name != null)
				{
					using (Stream resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
					{
						if (resourceStream != null)
						{
							using (IsolatedStorageFile myIsolatedStorage = IsolatedStorageFile.GetUserStoreForApplication())
							{
								using (IsolatedStorageFileStream fileStream = new IsolatedStorageFileStream(FileName, FileMode.Create, myIsolatedStorage))
								{
									using (BinaryWriter writer = new BinaryWriter(fileStream))
									{
										long length = resourceStream.Length;
										byte[] buffer = new byte[32];
										int readCount = 0;
										using (BinaryReader reader = new BinaryReader(resourceStream))
										{
											// read file in chunks in order to reduce memory consumption and increase performance
											while (readCount < length)
											{
												int actual = reader.Read(buffer, 0, buffer.Length);
												readCount += actual;
												writer.Write(buffer, 0, actual);
											}
										}
									}
								}
							}
							created = true;
						}
						else
						{
							this.CreateDatabase();
							created = true;
						}
					}
				}
				else
				{
					this.CreateDatabase();
					created = true;
				}
			}
			return created;
		}
		
		public bool LogDebug
		{
			set
			{
				if (value)
				{
					this.Log = new DebugWriter();
				}
			}
		}
		
		public static string ConnectionString = "Data Source=isostore:/Database.sdf";

		public static string ConnectionStringReadOnly = "Data Source=appdata:/Database.sdf;File Mode=Read Only;";

		public static string FileName = "Database.sdf";

		public DatabaseContext(string connectionString) : base(connectionString)
		{
			OnCreated();
		}
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPopravke(Popravke instance);
    partial void UpdatePopravke(Popravke instance);
    partial void DeletePopravke(Popravke instance);
    #endregion
		
		public System.Data.Linq.Table<Popravke> Popravke
		{
			get
			{
				return this.GetTable<Popravke>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute()]
	public partial class Popravke : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private double _Cijena;
		
		private System.DateTime _DatumPrijema;
		
		private string _Tip;
		
		private string _Vozilo;
		
		private string _Dijelovi;
		
		private System.DateTime _DatumZavrsetka;
		
		private string _StatusPopravke;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCijenaChanging(double value);
    partial void OnCijenaChanged();
    partial void OnDatumPrijemaChanging(System.DateTime value);
    partial void OnDatumPrijemaChanged();
    partial void OnTipChanging(string value);
    partial void OnTipChanged();
    partial void OnVoziloChanging(string value);
    partial void OnVoziloChanged();
    partial void OnDijeloviChanging(string value);
    partial void OnDijeloviChanged();
    partial void OnDatumZavrsetkaChanging(System.DateTime value);
    partial void OnDatumZavrsetkaChanged();
    partial void OnStatusPopravkeChanging(string value);
    partial void OnStatusPopravkeChanged();
    #endregion
		
		public Popravke()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cijena", Storage="_Cijena", DbType="Float NOT NULL")]
		public double Cijena
		{
			get
			{
				return this._Cijena;
			}
			set
			{
				if ((this._Cijena != value))
				{
					this.OnCijenaChanging(value);
					this.SendPropertyChanging();
					this._Cijena = value;
					this.SendPropertyChanged("Cijena");
					this.OnCijenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="datumPrijema", Storage="_DatumPrijema", DbType="DateTime NOT NULL")]
		public System.DateTime DatumPrijema
		{
			get
			{
				return this._DatumPrijema;
			}
			set
			{
				if ((this._DatumPrijema != value))
				{
					this.OnDatumPrijemaChanging(value);
					this.SendPropertyChanging();
					this._DatumPrijema = value;
					this.SendPropertyChanged("DatumPrijema");
					this.OnDatumPrijemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tip", Storage="_Tip", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Tip
		{
			get
			{
				return this._Tip;
			}
			set
			{
				if ((this._Tip != value))
				{
					this.OnTipChanging(value);
					this.SendPropertyChanging();
					this._Tip = value;
					this.SendPropertyChanged("Tip");
					this.OnTipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="vozilo", Storage="_Vozilo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Vozilo
		{
			get
			{
				return this._Vozilo;
			}
			set
			{
				if ((this._Vozilo != value))
				{
					this.OnVoziloChanging(value);
					this.SendPropertyChanging();
					this._Vozilo = value;
					this.SendPropertyChanged("Vozilo");
					this.OnVoziloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="dijelovi", Storage="_Dijelovi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Dijelovi
		{
			get
			{
				return this._Dijelovi;
			}
			set
			{
				if ((this._Dijelovi != value))
				{
					this.OnDijeloviChanging(value);
					this.SendPropertyChanging();
					this._Dijelovi = value;
					this.SendPropertyChanged("Dijelovi");
					this.OnDijeloviChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="datumZavrsetka", Storage="_DatumZavrsetka", DbType="DateTime NOT NULL")]
		public System.DateTime DatumZavrsetka
		{
			get
			{
				return this._DatumZavrsetka;
			}
			set
			{
				if ((this._DatumZavrsetka != value))
				{
					this.OnDatumZavrsetkaChanging(value);
					this.SendPropertyChanging();
					this._DatumZavrsetka = value;
					this.SendPropertyChanged("DatumZavrsetka");
					this.OnDatumZavrsetkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="statusPopravke", Storage="_StatusPopravke", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string StatusPopravke
		{
			get
			{
				return this._StatusPopravke;
			}
			set
			{
				if ((this._StatusPopravke != value))
				{
					this.OnStatusPopravkeChanging(value);
					this.SendPropertyChanging();
					this._StatusPopravke = value;
					this.SendPropertyChanged("StatusPopravke");
					this.OnStatusPopravkeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
